name: Build Image 

on: 
  #schedule:
  #  - cron: '52 14 * * 1'
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      mode:
        description: 'Manual Build'  

env:
  REGISTRY: ghcr.io

jobs:

  Build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write    
    steps:

    - name: "Set IMAGE Environmental Variable"
      run: |
        echo "IMAGE=${REGISTRY}/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}" >> $GITHUB_ENV

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: "Log in to the Container Registry"
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}      
      
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v2

    - name: "Build Local Container"
      uses: docker/build-push-action@v3
      with:
        tags: ${{ env.IMAGE }}
        push: true
        load: false                      
